### ISSUE TITLE
One FoolProof assignment not syncing

### ISSUE THREAD

**Issue by kenburbank** [jb-1980/khanimport#2]
The skill I'm Broke in FoolProof does not post
 Course 1212
Assignment 166287

Student is Lauren Taylor 

Student 79174

**Comment by jb-1980** [comment]
Is this posting for any other student?

**Comment by kenburbank** [comment]
No, a different student wrote me so I posted it manually and then hunted for another example.  Lauren completed it on 2/9.

**Comment by jb-1980** [comment]
It is just being true to its title :laughing:

**Comment by kenburbank** [comment]
I hate to spoil such an outstanding pun, but I just found others.  I have the foolproof.json from last night and I'm checking it out.

**Comment by kenburbank** [comment]
This student is on last night's .json
78474  
But no entry under  assig 162222 or 162229

**Comment by kenburbank** [comment]
Disregard, the pun stands.  The student is on last night's .json but assignment 166287 is not.

**Comment by jb-1980** [comment]
I think I found the issue:

![image](https://cloud.githubusercontent.com/assets/2569898/23466340/045dc1ac-fe58-11e6-9423-91ae979aa627.png)

**Comment by kenburbank** [comment]
I had a Khan skill drop out also.  What would make ELMS randomly drop export IDs?  I should have checked that first.  Thanks.
