### ISSUE TITLE
Grade syncer needs update for Moneyskill revision

### ISSUE THREAD

**Issue by kenburbank** [jb-1980/khanimport#4]
The front end of moneyskill has changed.  This was the previous url that returns an error:

https://lms.moneyskill.org/teachers/login.cfm?so=1

https://lms.moneyskill.org/teachers

It appears that they did away with teacher numbers and renumbered all the classes.  Here are links to all of the gradebooks. 

MFL A (1242):  https://lms.moneyskill.org/teachers/class/1016/students/grades
MFL B (1253):  https://lms.moneyskill.org/teachers/class/1017/students/grades
Fin Lit 1 (1292):  https://lms.moneyskill.org/teachers/class/1019/students/grades
Fin Lit 2 (1305): https://lms.moneyskill.org/teachers/class/1020/students/grades

@jb-1980 Hope it's a relatively quick fix.  Please keep me informed.  Thanks!

**Comment by kenburbank** [comment]
I changed the Moneyskill course ID numbers in Grade Syncer to the new ones, but won't run.  @jb-1980 Perhaps just the new login protocol noted above?

**Comment by jb-1980** [comment]
I had to refactor it to use the new endpoints, which also require authentication. But it should be working now. It successfully ran Financial Literacy 1 1708. I did not actually do any spot checking to make sure the grades updated, but I am sure you can take it from there.

**Comment by kenburbank** [comment]
Thanks, but I didn't mean for you to do it on your break, but I appreciate it.


What is the login and password for your tracker?




Ken Burbank

Director of Math Education, Sequoia Choice

Phone:  480-254-7698

Virtual classroom link: https://zoom.us/j/6937843649<http://www.tinyurl.com/sequoiachoicemath>

 [1468527002671_sequoia-choice-logo_tree_200r1.png]

Our Mission is to provide a caring environment of high expectations, individualized attention, and great teaching via a distance learning delivery system that is sufficiently adaptable to help K-12 students in traditional and non-traditional educational settings achieve their maximum academic potential and life goals.

AMDG


________________________________

**Comment by kenburbank** [comment]
Hi @jb-1980  The Moneyskill import isn't working.
Case:  Trestyn Thompson  #81311  Course ID #1292
Moneyskill course 1019

Syncer says it ran with cron job overnight (10/18) but student has two scores from yesterday not posted
![trestyn](https://user-images.githubusercontent.com/22966552/31729903-3e782d30-b3e5-11e7-990a-eb91b7367421.GIF)

**Comment by kenburbank** [comment]
I just ran grade syncer for MFL A gradebook # 1242 (at 9:45 on 10/23).  It takes a while and says it ran, but no updated grades.

**Comment by jb-1980** [comment]
Curious, are you receiving the emails about unmatched students? It appears that those warnings are being sent to the sequoiachoicemath account, not to the personal emails. I mention it, because it appears that everything is syncing as expected, but there are a large number of students who don't match up. It may be that those students are not receiving updated grades because their is a mismatch in their names between ELMS and Moneyskill. I am still trying to investigate further.

**Comment by jb-1980** [comment]
Found the bug. It was casting a key as an integer instead of a string, and thus messed up the look up. Anyways, it should be working now.

**Comment by kenburbank** [comment]
Ah, I didn't know they went to that email.  Yes, there are error messages there.

Here is one for math for financial literacy A.  Note three things:
Possible points is now a student name it is searching for.
This list is not the full class, but it must time out or quit.
The names names are First Last, but I enter them as Last, First.  Before they changed Moneyskill to the new format, was this how the names were presented?

**Comment by kenburbank** [comment]
Didn't paste in the sample

The following students did not have a match from ELMS:
Possible Points
Dyanicia Santamaria
Esmeralda Soto Avendado
Serge Baraka
Samantha Bernice Salinas
Clarissa Chamberlain
Gerson Chonay Yool

**Comment by kenburbank** [comment]
No joy.  I ran a test of the grade syncer and no update.  It was a 90 on moneyskill #1 for Ana Coronado Lopez in Fl 2 gradebook # 1305.  I will leave the grade blank in the gradebook to see if the cron job posts it tonight.

**Comment by jb-1980** [comment]
Doh! I feel like a fool. I have been butting my head against this for hours, and just realized that I forgot to push the changes to the production server. So of course you will have no joy, because the code wasn't there yet.

I just checked with Ana's grade, and everything is copacetic. You can reopen if you continue to see issues.
