### ISSUE TITLE
Moneyskill benchmark not syncing

### ISSUE THREAD

**Issue by kenburbank** [jb-1980/khanimport#7]
It may be the new format, but the Moneyskill posttest is not syncing to the post export ID in elms.  This is how the new gradebook in moneyskill has it captioned:

![image](https://user-images.githubusercontent.com/22966552/32630561-49466156-c55a-11e7-88ec-d7a56246fdeb.png)

**Comment by jb-1980** [comment]
Okay, I am looking into it. But please move this issue to the gradesyncer repo at https://github.com/SequoiaChoice/GradeSyncer/issues. The khanimport is a moodle plugin I have not touched in years.

**Comment by kenburbank** [comment]
done  thanks!
